import { NavLink } from "../core/layouts/types";
// import {
//   adminCat,
//   builderCat,
//   manufacturingCat,
//   merchantCat,
// } from "../core/utils/constants";
import { UserRole } from "../redux/features/user-slice";
import paths from "./paths";

export const navigation: NavLink[] = [
  // {
  //   id: "dailyReports",
  //   type: "link",
  //   title: "Daily Reports",
  //   path: paths.DAILY_REPORTS,
  //   category: [],
  //   role: [
  //     UserRole.Manager,
  //     UserRole.Leader,
  //     UserRole.Contributor,
  //     UserRole.Member,
  //   ],
  // },
  // {
  //   id: "weeklyReports",
  //   type: "link",
  //   title: "Weekly Reports",
  //   path: paths.WEEKLY_REPORTS,
  //   category: [],
  //   role: [
  //     UserRole.Manager,
  //     UserRole.Leader,
  //     UserRole.Contributor,
  //     UserRole.Member,
  //   ],
  // },
  // {
  //   id: "categories",
  //   type: "link",
  //   title: "Categories",
  //   path: paths.CATEGORIES,
  //   category: [],
  //   role: [UserRole.Manager, UserRole.Leader],
  // },
  // {
  //   id: "categoriesManagement",
  //   type: "link",
  //   title: "Categories",
  //   category: [],
  //   role: [UserRole.Admin, UserRole.Supervisor],
  //   child: [
  //     {
  //       id: `${paths.CATEGORIES}/${adminCat.name}/${adminCat.id}`,
  //       type: "link",
  //       title: adminCat.name,
  //       path: `${paths.CATEGORIES}/${adminCat.name}/${adminCat.id}`,
  //       category: [adminCat.id],
  //       role: [UserRole.Admin, UserRole.Supervisor],
  //     },
  //     {
  //       id: `${paths.CATEGORIES}/${manufacturingCat.name}/${manufacturingCat.id}`,
  //       type: "link",
  //       title: manufacturingCat.name,
  //       path: `${paths.CATEGORIES}/${manufacturingCat.name}/${manufacturingCat.id}`,
  //       category: [adminCat.id, manufacturingCat.id],
  //       role: [UserRole.Admin, UserRole.Supervisor],
  //     },
  //     {
  //       id: `${paths.CATEGORIES}/${merchantCat.name}/${merchantCat.id}`,
  //       type: "link",
  //       title: merchantCat.name,
  //       path: `${paths.CATEGORIES}/${merchantCat.name}/${merchantCat.id}`,
  //       category: [adminCat.id, merchantCat.id],
  //       role: [UserRole.Admin, UserRole.Supervisor],
  //     },
  //     {
  //       id: `${paths.CATEGORIES}/${builderCat.name}/${builderCat.id}`,
  //       type: "link",
  //       title: builderCat.name,
  //       path: `${paths.CATEGORIES}/${builderCat.name}/${builderCat.id}`,
  //       category: [adminCat.id, builderCat.id],
  //       role: [UserRole.Admin, UserRole.Supervisor],
  //     },
  //   ],
  // },
  // {
  //   id: "workCalendar",
  //   type: "link",
  //   title: "Work Calendar",
  //   path: paths.WORK_CALENDAR,
  //   category: [adminCat.id],
  //   role: [],
  // },
  // {
  //   id: "usersManagement",
  //   type: "section",
  //   title: "Users Management",
  //   category: [adminCat.id],
  //   role: [UserRole.Admin, UserRole.Supervisor],
  // },
  // {
  //   id: "users",
  //   type: "link",
  //   title: "Users",
  //   path: paths.USERS,
  //   category: [adminCat.id],
  //   role: [UserRole.Admin, UserRole.Supervisor],
  // },
  // {
  //   id: "addUser",
  //   type: "link",
  //   title: "Add User",
  //   path: paths.ADD_USER,
  //   category: [adminCat.id],
  //   role: [UserRole.Admin, UserRole.Supervisor],
  // },
  {
    id: "data",
    type: "section",
    title: "Data",
    category: [],
    role: [],
  },
  // {
  //   id: "reports",
  //   type: "link",
  //   title: "Export Reports",
  //   path: paths.EXPORT_REPORTS,
  //   category: [],
  //   role: [],
  // },
  // {
  //   id: "schedules",
  //   type: "link",
  //   title: "Schedule Reports",
  //   path: paths.SCHEDULE_REPORTS,
  //   category: [],
  //   role: [],
  // },
  // {
  //   id: "addschedule",
  //   type: "link",
  //   title: "Add Schedule Reports",
  //   path: paths.ADD_SCHEDULE_REPORT,
  //   category: [],
  //   role: [],
  // },
  // {
  //   id: "incidentsdashboard",
  //   type: "link",
  //   title: "Customer support",
  //   path: paths.INCIDENTS_DASHBOARD,
  //   category: [],
  //   role: [],
  // },
  {
    id: "taskManagement",
    type: "link",
    title: "Task Management",
    category: [],
    role: [],
    child: [],
  },
  {
    id: "tasktypes",
    type: "link",
    title: "Task Types",
    path: paths.TASK_TYPES,
    category: [],
    role: [],
  },
  {
    id: "addtasktype",
    type: "link",
    title: "Add Task Type",
    path: paths.ADD_TASK_TYPE,
    category: [],
    role: [],
  },
  {
    id: "taskgrouptypes",
    type: "link",
    title: "Task Group Types",
    path: paths.TASK_GROUP_TYPES,
    category: [],
    role: [],
  },
  {
    id: "addtaskgrouptype",
    type: "link",
    title: "Add Task Group Type",
    path: paths.ADD_TASK_GROUP_TYPE,
    category: [],
    role: [],
  },
  {
    id: "subjobManagement",
    type: "link",
    title: "Subjob Management",
    category: [],
    role: [],
    child: [],
  },
  {
    id: "addsubjobtype",
    type: "link",
    title: "Add Sub Job Type",
    path: paths.ADD_SUB_JOB_TYPE,
    category: [],
    role: [],
  },
  {
    id: "subjobtypes",
    type: "link",
    title: "Sub Job Types",
    path: paths.SUB_JOB_TYPES,
    category: [],
    role: [],
  },
  {
    id: "addsubjobcategory",
    type: "link",
    title: "Add Sub Job Category",
    path: paths.ADD_SUB_JOB_CATEGORY,
    category: [],
    role: [],
  },
  {
    id: "subjobcategories",
    type: "link",
    title: "Sub Job Categories",
    path: paths.SUB_JOB_CATEGORIES,
    category: [],
    role: [],
  },
  {
    id: "jobManagement",
    type: "link",
    title: "Job Management",
    category: [],
    role: [],
    child: [],
  },
  {
    id: "addjobtype",
    type: "link",
    title: "Add Job Type",
    path: paths.ADD_JOB_TYPE,
    category: [],
    role: [],
  },
  {
    id: "jobtypes",
    type: "link",
    title: "Job Types",
    path: paths.JOB_TYPES,
    category: [],
    role: [],
  },
  {
    id: "job",
    type: "link",
    title: "Jobs",
    path: paths.JOBS,
    category: [],
    role: [],
  },
  {
    id: "job",
    type: "link",
    title: "Add Job",
    path: paths.ADD_JOB,
    category: [],
    role: [],
  },
];
