import { NOTFOUND } from "dns";

const paths = {
  DEFAULT: "/",
  LOGIN: "/auth/login",
  DAILY_REPORTS: "/reports/daily-reports",
  WEEKLY_REPORTS: "/reports/weekly-reports",
  TASKS: "/task-management/tasks",
  PROFILE: "/settings/profile",
  RECURRENCES: "/settings/task-properties/recurrences",
  //JOB_TYPES: "/settings/task-properties/job-types",
  RELATIONSHIP_STATUS: "/settings/task-properties/relationship-status",
  REQUEST_TYPES: "/settings/task-properties/request-types",
  ISSUES: "/settings/summary-properties/issues",
  SUPPORT_RESOURCES: "/settings/summary-properties/support-resources",
  REASONS: "/settings/summary-properties/reasons",
  CHALLENGES: "/settings/summary-properties/challenges",
  MY_FILES: "/documents/my-files",
  SHARED: "/documents/shared",
  VIEWER: "/documents/viewer",
  CATEGORIES: "/categories",
  GROUP_TEAMS: "/group-teams",
  MEMBER: "/member",
  DESIGN_MEMBER: "/design-member",
  TEAM_MEMBERS: "/team-members",
  USERS: "/user-management/users",
  ADD_USER: "/user-management/add-user",
  EXPORT_REPORTS: "/data/export-reports",
  CHANGE_PASSWORD: "/settings/change-password",
  UNAUTHORIZED: "/unauthorized",
  NOT_FOUND: "/not-found",
  ADD_SCHEDULE_REPORT: "/data/schedule-reports/add-schedule-report",
  SCHEDULE_REPORTS: "/data/schedule-reports",
  WORK_CALENDAR: "/work-calendar",
  INCIDENTS: "/incidents",
  ADD_INCIDENT: "/add-incident",
  INCIDENTS_DASHBOARD:"/incidents-dashboard",
  TASK_TYPES: "/task-types",
  ADD_TASK_TYPE: "/add-task-type",
  TASK_GROUP_TYPES: "/task-group-types",
  ADD_TASK_GROUP_TYPE: "/add-task-group-type",
  SUB_JOB_TYPES: "/sub-job-types",
  ADD_SUB_JOB_TYPE: "/add-sub-job-type",
  SUB_JOB_CATEGORIES: "/sub-job-categories",
  ADD_SUB_JOB_CATEGORY: "/add-sub-job-category",
  ADD_JOB_TYPE: "/add-job-type",
  JOB_TYPES: "/job-types",
  JOBS: "/jobs",
  ADD_JOB: "/add-job"
};

export default paths;
